### ISSUE TITLE
Fix typos in names

### ISSUE THREAD

**Issue by valeriodigregorio** [kingargyle/iaskirmish-data#3]
See following diffs;

https://github.com/valeriodigregorio/iaskirmish-data/commit/3285fd5f71968a8e9eb7b452bde812599d97d7b8

https://github.com/valeriodigregorio/iaskirmish-data/commit/90eb835ef2a3229e2be20038c1f54e52a676fd2c

**Comment by kingargyle** [comment]
Can you open a pull request and I can just merge the changes from there.

**Comment by valeriodigregorio** [comment]
Ok I'll do asap!
